<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="JARVIS" ignored="1" name="RetryMultiple(failed)" tests="3" failures="1" timestamp="2022-05-11T15:53:23 IST" time="0.059" errors="0">
  <testcase name="tc1" time="0.01" classname="runTimeRetryFailedTC.Test01">
    <skipped/>
  </testcase> <!-- tc1 -->
  <testcase name="tc1" time="0.001" classname="runTimeRetryFailedTC.Test01">
    <skipped/>
  </testcase> <!-- tc1 -->
  <testcase name="tc1" time="0.001" classname="runTimeRetryFailedTC.Test01">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at runTimeRetryFailedTC.Test01.tc1(Test01.java:9)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- tc1 -->
  <testcase name="tc2" time="0.0" classname="runTimeRetryFailedTC.Test01">
    <ignored/>
  </testcase> <!-- tc2 -->
</testsuite> <!-- RetryMultiple(failed) -->
